### ISSUE TITLE
unsafe std::mem::transmute ?

### ISSUE THREAD

**Issue by tissatussa** [jw1912/monty#103]
i tried to compile your source but i get this error.
btw. the README states `EVALFILE=<path to network file>` so i copied the file `net.network` from the folder `resources` into the root folder ?! (but i guess this is wrong)

```
~/Compiled/monty-1.0.0$ make chess EXE=./Monty-v1.0.0 EVALFILE=./net.network
cargo rustc --release --package monty --bin monty -- -C target-cpu=native --emit link=./Monty-v1.0.0
   Compiling monty v1.0.0 (/home/roelof/Compiled/monty-1.0.0)
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> src/bin/monty.rs:9:29
  |
9 | const NETS: Nets = unsafe { std::mem::transmute(*include_bytes!("../../resources/net.network")) };
  |                             ^^^^^^^^^^^^^^^^^^^
  |
  = note: source type: `[u8; 21022697]` (168181576 bits)
  = note: target type: `Nets` (153703616 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `monty` (bin "monty") due to 1 previous error
make: *** [Makefile:14: chess] Error 101
```

**Comment by jw1912** [comment]
@tissatussa this is not unsafe, as you can see it causes a compile error, thereby being completely safe.

Where did you get the network from?

**Comment by tissatussa** [comment]
> Where did you get the network from? It looks like you're just using an incorrect network.

as i wrote : i copied the file `net.network` from the folder resources into the root folder, because it was unclear to me where to get a network file .. should i use some .nnue file ? Many types exist !

what does `../../resources/net.network` mean ?

**Comment by jw1912** [comment]
> as i wrote : i copied the file `net.network` from the folder resources into the root folder

There is no `net.network` file in this repository.

**Comment by jw1912** [comment]
@tissatussa the networks (for chess) can be found in Monty's network section at https://chess.swehosting.se//networks/Monty/ (briefly down ATM for some reason, hopefully resolved soon), the current master network will have a big green star next to it.

**Comment by tissatussa** [comment]
i had to register on that website, but until now i see :

_Account has not been enabled. Contact an Administrator_

i have no clue .. do you ?

**Comment by tissatussa** [comment]
i managed to get that network file (by using Discord) and i compiled your v1.0.0 source successfully .. in CuteChess Monty plays a good game ! Any idea of its rating ? I guess it's about 2800+

**Comment by jw1912** [comment]
> i managed to get that network file (by using Discord) and i compiled your v1.0.0 source successfully .. in CuteChess Monty plays a good game ! Any idea of its rating ? I guess it's about 2800+

The current development version is around 3150-3200 CCRL blitz (based on tests against Altair 5 and Princess 16).
