### ISSUE TITLE
Stop command not working

### ISSUE THREAD

**Issue by joergoster** [jw1912/monty#97]
It looks like Monty doesn't respond to the stop command in infinite analysis mode.

> ucinewgame
> isready
> readyok
> position startpos
> go infinite
> info string attempting to reuse tree
> info string searching for subtree
> info string no subtree found
> info string tree processing took 592 microseconds
> info depth 1 score cp 86 time 3 nodes 22 nps 5748 hashfull 0 pv c2c4
> info depth 2 score cp 82 time 9 nodes 116 nps 11954 hashfull 0 pv d2d4 d7d5
> info depth 3 score cp 99 time 28 nodes 1252 nps 44175 hashfull 7 pv e2e4 c7c5 b1c3
> info depth 4 score cp 78 time 82 nodes 7030 nps 85401 hashfull 40 pv d2d4 d7d5 g1f3 g8f6
> info depth 5 score cp 82 time 205 nodes 22033 nps 107415 hashfull 126 pv d2d4 g8f6 c2c4 e7e6 g1f3
> info depth 6 score cp 77 time 450 nodes 50819 nps 112709 hashfull 290 pv d2d4 g8f6 c2c4 c7c5 d4d5 g7g6
> info depth 7 score cp 73 time 980 nodes 110130 nps 112314 hashfull 630 pv d2d4 g8f6 c2c4 e7e6 b1c3 d7d5 g1f3
> info depth 8 score cp 66 time 2080 nodes 231819 nps 111399 hashfull 1000 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 e2e3 f8e7
> info depth 9 score cp 63 time 3516 nodes 373933 nps 106339 hashfull 1000 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 b1c3 f8b4 e2e3
> info depth 10 score cp 62 time 10170 nodes 1067463 nps 104961 hashfull 1000 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 b1c3 f8b4 e2e3 e8g8
> info depth 11 score cp 66 time 52158 nodes 5244213 nps 100543 hashfull 1000 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 f1d3 g8f6 g1f3 f8d6 d1e2
> info depth 11 score cp 62 time 102585 nodes 10000000 nps 97480 hashfull 1000 pv
> bestmove e2e4
> stop
> stop

As you can see at the end I tried to send 'stop' twice. Input seems to be blocked.

Expected behavior: stop the search immediately after receiving the 'stop' signal.

**Comment by jw1912** [comment]
@joergoster yeah I forgot to add stop support before this release, it'll be done before the next one.
